### PR TITLE
Fix #1319 Allow users to change the target language of their translation

### LINKED ISSUE #1319: Allow users to change the target language of their translation
See unfoldingWord-dev/ts-requirements#33 for full details

If Jack starts translating in a language x then Jill starts translating in a language Y but then realize Jack chose the wrong language code they need a way to fix that and merge their translations.

Providing a setting some place where you can change the target language would solve this. However, we probably don't want to make this too prominent to avoid people accidentally switching their languages, and be sure to offer plenty of warnings and explainations.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fixes #1319 Allow users to change the target language of their translation 

Changes in this pull request:
- changed NewTargetTranslationActivity to accept parameters to select and change target language.

### CODE REVIEW

File: app/src/main/java/com/door43/translationstudio/newui/newtranslation/NewTargetTranslationActivity.java [hunk 1]
```diff
@@ -153,12 +160,24 @@ public boolean onCreateOptionsMenu(Menu menu) {
...
+            invalidateOptionsMenu();
+        } else { // just change the target language
+            Translator translator = App.getTranslator();
+            TargetTranslation targetTranslation = translator.getTargetTranslation(mTargetTranslationId);
+            String targetTranslationId = targetTranslation.getId();
+
+            targetTranslation.changeTargetLanguage(mSelectedTargetLanguage);
+            String newTargetTranslationId = targetTranslation.getId();
+
+            translator.renameTargetTranslation(targetTranslationId, newTargetTranslationId);
```
Comment (neutrinog) [inline app/src/main/java/com/door43/translationstudio/newui/newtranslation/NewTargetTranslationActivity.java]: @PhotoNomad0 there's already a method called `normalizePath()` that does this same thing with some extra error checking. I went ahead and switched out the `renameTargetTranslation` method for it.
