### PR TITLE
Fix #1822 QA fail - popup keyboard on search

### LINKED ISSUE #1822: Automatically display keyboard when user clicks Search on 3dot menu
Currently focus is set to the input field but the keyboard is not being displayed.

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Fix #1822 popup keyboard on search

Changes in this pull request:
- TargetTranslationActivity: now saves handle to search edit text.  Fixed issue that notification of data change was closing keyboard as soon as search bar is brought up.  Now we don't automatically close the keyboard if the search bar is up and the search edit text has focus.

---
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-android/1866)

### CODE REVIEW

File: app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java [hunk 1]
```diff
@@ -618,24 +619,24 @@ public void onClick(View v) {
...
+            Handler hand = new Handler(Looper.getMainLooper());
+            hand.post(new Runnable() {
+                @Override
+                public void run() {
+                    mSearchEditText.setFocusableInTouchMode(true);
+                    mSearchEditText.requestFocus();
 
-            }
-        });
+                    Handler hand = new Handler(Looper.getMainLooper());
```
Comment (neutrinog) [inline app/src/main/java/com/door43/translationstudio/ui/translate/TargetTranslationActivity.java]: Why are we executing another handler? We are already on the main thread. See line 623 above.
